theme: minima
markdown: kramdown

collections:
  concepts:
    output: true
  equations:
    output: true
  notes:
    output: true
  diagrams:
    output: true
  papers:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
